### ISSUE TITLE
Hello, there is a problem with the plug-in

### ISSUE THREAD

**Issue by Coolrui1816** [opa334/opa334.github.io#1]
"Crane" developed by you

I had an error starting the app

Tips:
It's pretty sure "CraneSupport.dylib" not loaded into your "securityd"
Crane disabled

How to solve this problem？thank

**Comment by Coolrui1816** [comment]
[https://raw.githubusercontent.com/Coolrui1816/QuanX/master/img/Help/IMG_3216.PNG](url)

**Comment by opa334** [comment]
this is not the right place for support

nonetheless, if your jailbreak is unc0ver, make sure you got the latest version of it
